on: push
name: Deploy website on push
jobs:
 web-deploy:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
   - name: Get latest code
     uses: actions/checkout@v2

   - name: Sync files
     uses: SamKirkland/FTP-Deploy-Action@4.3.0
     with:
       server: 178.16.128.32
       server-dir: /public_html/mediatekformation/
       username: u482619961
       password: ${{ secrets.ftp_password }}
